name: frontend

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: frontend

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::945788247695:oidc-provider/token.actions.githubusercontent.com
          aws-region: ap-northeast-1

      - run: aws s3 sync . s3://udemy-github-actions-s3-oshima --exact-timestamps --region ap-northeast-1